export type PickCategory = 'Top Picks' | 'High Confidence' | 'Value' | 'Trending' | 'Market Movers' | 'My Saved';
export type PickSort = 'Highest Confidence' | 'Best L5' | 'Best L10' | 'Best L20' | 'Best L40' | 'Best 2026' | 'Best Value' | 'Biggest Market Move';

export interface PickRecord {
  id: string;
  playerId: string;
  mlbPlayerId?: number;
  playerName: string;
  playerImageUrl: string;
  team: string;
  teamId?: number;
  teamLogoUrl: string;
  opponent: string;
  opponentTeamId?: number;
  market: string;
  line: string;
  side: 'Over' | 'Under';
  odds: string;
  openingOdds: string;
  l5: number;
  l10: number;
  l20: number;
  l40: number;
  season2026: number;
  confidence: number;
  projectedProbability: number;
  impliedProbability: number;
  projectedEdge: number;
  recentFormScore: number;
  matchupScore: number;
  marketMovementScore: number;
  opportunityScore: number;
  projectedPlateAppearances: string;
  weatherSummary: string;
  parkFactor: string;
  pitcherSummary: string;
  riskFactors: string[];
  category: PickCategory;
  insight: string;
  marketMovement: string;
  description: string;
  researchHref: string;
}

const basePicks: Omit<PickRecord, 'opportunityScore' | 'category' | 'insight' | 'marketMovement' | 'description' | 'researchHref'>[] = [
  {
    id: 'judge-hr',
    playerId: 'aaron-judge',
    mlbPlayerId: 592450,
    playerName: 'Aaron Judge',
    playerImageUrl: 'AJ',
    team: 'Yankees',
    teamId: 147,
    teamLogoUrl: 'NYY',
    opponent: 'vs Red Sox',
    opponentTeamId: 111,
    market: 'Home Runs',
    line: 'Over 0.5',
    side: 'Over',
    odds: '-120',
    openingOdds: '+110',
    l5: 80,
    l10: 70,
    l20: 75,
    l40: 68,
    season2026: 72,
    confidence: 86,
    projectedProbability: 63,
    impliedProbability: 54,
    projectedEdge: 9.4,
    recentFormScore: 9.1,
    matchupScore: 8.6,
    marketMovementScore: 7.8,
    projectedPlateAppearances: '5.4',
    weatherSummary: 'Clear, calm winds',
    parkFactor: 'High HR park',
    pitcherSummary: 'Garrett Crochet: 26% K-rate, 3.8 HR/9',
    riskFactors: ['Recent fastball approach', 'Lefty platoon risk'],
  },
  {
    id: 'soto-hits',
    playerId: 'juan-soto',
    mlbPlayerId: 665742,
    playerName: 'Juan Soto',
    playerImageUrl: 'JS',
    team: 'Yankees',
    teamId: 147,
    teamLogoUrl: 'NYY',
    opponent: 'vs Red Sox',
    opponentTeamId: 111,
    market: 'Hits',
    line: 'Over 0.5',
    side: 'Over',
    odds: '-115',
    openingOdds: '-105',
    l5: 72,
    l10: 69,
    l20: 73,
    l40: 66,
    season2026: 68,
    confidence: 78,
    projectedProbability: 58,
    impliedProbability: 53,
    projectedEdge: 5.2,
    recentFormScore: 8.2,
    matchupScore: 7.7,
    marketMovementScore: 6.6,
    projectedPlateAppearances: '4.8',
    weatherSummary: 'Warm, slight breeze',
    parkFactor: 'Neutral',
    pitcherSummary: 'Crochet has allowed 3+ hits in 6 of 8 starts',
    riskFactors: ['Low walk rate', 'Early count leverage'],
  },
  {
    id: 'ohtani-tb',
    playerId: 'shohei-ohtani',
    mlbPlayerId: 660271,
    playerName: 'Shohei Ohtani',
    playerImageUrl: 'SO',
    team: 'Dodgers',
    teamId: 119,
    teamLogoUrl: 'LAD',
    opponent: 'vs Giants',
    opponentTeamId: 137,
    market: 'Total Bases',
    line: 'Over 1.5',
    side: 'Over',
    odds: '-125',
    openingOdds: '-105',
    l5: 76,
    l10: 74,
    l20: 79,
    l40: 71,
    season2026: 74,
    confidence: 84,
    projectedProbability: 61,
    impliedProbability: 56,
    projectedEdge: 5.3,
    recentFormScore: 8.8,
    matchupScore: 8.1,
    marketMovementScore: 7.2,
    projectedPlateAppearances: '5.2',
    weatherSummary: 'Wind out to left',
    parkFactor: 'Boosts fly balls',
    pitcherSummary: 'Blake Snell: 27% K-rate, 4.1 HR/9',
    riskFactors: ['Weather can shift', 'High variance'],
  },
  {
    id: 'torres-hits',
    playerId: 'pablo-torres',
    playerName: 'Pablo Torres',
    playerImageUrl: 'PT',
    team: 'Brewers',
    teamLogoUrl: 'MIL',
    opponent: 'vs Pirates',
    market: 'Hits',
    line: 'Over 0.5',
    side: 'Over',
    odds: '-110',
    openingOdds: '-120',
    l5: 64,
    l10: 63,
    l20: 66,
    l40: 60,
    season2026: 65,
    confidence: 67,
    projectedProbability: 54,
    impliedProbability: 52,
    projectedEdge: 2.4,
    recentFormScore: 6.8,
    matchupScore: 7.1,
    marketMovementScore: 5.4,
    projectedPlateAppearances: '4.1',
    weatherSummary: 'Mild, no major wind',
    parkFactor: 'Neutral',
    pitcherSummary: 'Mitch Keller has a 6.4% walk rate',
    riskFactors: ['Low-top-end upside'],
  },
  {
    id: 'skenes-k',
    playerId: 'paul-skenes',
    playerName: 'Paul Skenes',
    playerImageUrl: 'PS',
    team: 'Pirates',
    teamLogoUrl: 'PIT',
    opponent: 'vs Cubs',
    market: 'Strikeouts',
    line: 'Over 6.5',
    side: 'Over',
    odds: '-125',
    openingOdds: '+110',
    l5: 71,
    l10: 68,
    l20: 70,
    l40: 67,
    season2026: 77,
    confidence: 81,
    projectedProbability: 59,
    impliedProbability: 56,
    projectedEdge: 3.1,
    recentFormScore: 8.5,
    matchupScore: 8.3,
    marketMovementScore: 7.9,
    projectedPlateAppearances: 'N/A',
    weatherSummary: 'Windy, cool',
    parkFactor: 'Favorable for K rate',
    pitcherSummary: 'Cubs projected to chase 4-seamers',
    riskFactors: ['Pitch count upside'],
  },
  {
    id: 'betts-hits',
    playerId: 'mookie-betts',
    playerName: 'Mookie Betts',
    playerImageUrl: 'MB',
    team: 'Dodgers',
    teamLogoUrl: 'LAD',
    opponent: 'vs Giants',
    market: 'Hits',
    line: 'Over 0.5',
    side: 'Over',
    odds: '-115',
    openingOdds: '-105',
    l5: 70,
    l10: 68,
    l20: 72,
    l40: 69,
    season2026: 71,
    confidence: 75,
    projectedProbability: 57,
    impliedProbability: 53,
    projectedEdge: 4.1,
    recentFormScore: 7.9,
    matchupScore: 7.4,
    marketMovementScore: 6.2,
    projectedPlateAppearances: '4.9',
    weatherSummary: 'Calm, mild',
    parkFactor: 'Neutral',
    pitcherSummary: 'Snell has allowed 8+ hits in 4 of last 7',
    riskFactors: ['Ground-ball risk'],
  },
  {
    id: 'henderson-hit',
    playerId: 'gunnar-henderson',
    playerName: 'Gunnar Henderson',
    playerImageUrl: 'GH',
    team: 'Orioles',
    teamLogoUrl: 'BAL',
    opponent: 'vs Astros',
    market: 'Hits',
    line: 'Over 0.5',
    side: 'Over',
    odds: '-120',
    openingOdds: '-100',
    l5: 69,
    l10: 67,
    l20: 71,
    l40: 64,
    season2026: 70,
    confidence: 72,
    projectedProbability: 55,
    impliedProbability: 55,
    projectedEdge: 0.3,
    recentFormScore: 7.2,
    matchupScore: 7.0,
    marketMovementScore: 6.0,
    projectedPlateAppearances: '4.6',
    weatherSummary: 'Indoor',
    parkFactor: 'Neutral',
    pitcherSummary: 'Hunter Brown: 25% K-rate',
    riskFactors: ['Low edge, high variance'],
  },
  {
    id: 'turner-sb',
    playerId: 'trea-turner',
    playerName: 'Trea Turner',
    playerImageUrl: 'TT',
    team: 'Phillies',
    teamLogoUrl: 'PHI',
    opponent: 'vs Marlins',
    market: 'Stolen Bases',
    line: 'Over 0.5',
    side: 'Over',
    odds: '-130',
    openingOdds: '-110',
    l5: 67,
    l10: 66,
    l20: 68,
    l40: 64,
    season2026: 69,
    confidence: 70,
    projectedProbability: 53,
    impliedProbability: 56,
    projectedEdge: -3.4,
    recentFormScore: 6.5,
    matchupScore: 6.9,
    marketMovementScore: 5.8,
    projectedPlateAppearances: '4.4',
    weatherSummary: 'Humid, warm',
    parkFactor: 'Neutral',
    pitcherSummary: 'Edward Cabrera: 15% stolen base rate',
    riskFactors: ['Catcher pop time risk'],
  },
  {
    id: 'valdez-eras',
    playerId: 'framber-valdez',
    playerName: 'Framber Valdez',
    playerImageUrl: 'FV',
    team: 'Astros',
    teamLogoUrl: 'HOU',
    opponent: 'vs Orioles',
    market: 'Earned Runs',
    line: 'Under 1.5',
    side: 'Under',
    odds: '+105',
    openingOdds: '+120',
    l5: 60,
    l10: 62,
    l20: 63,
    l40: 64,
    season2026: 66,
    confidence: 74,
    projectedProbability: 57,
    impliedProbability: 49,
    projectedEdge: 8.1,
    recentFormScore: 7.2,
    matchupScore: 7.7,
    marketMovementScore: 6.8,
    projectedPlateAppearances: 'N/A',
    weatherSummary: 'Indoor park',
    parkFactor: 'Neutral',
    pitcherSummary: 'Orioles are 24th in contact rate vs lefties',
    riskFactors: ['Bullpen leverage risk'],
  },
  {
    id: 'judge-rbi',
    playerId: 'aaron-judge',
    playerName: 'Aaron Judge',
    playerImageUrl: 'AJ',
    team: 'Yankees',
    teamLogoUrl: 'NYY',
    opponent: 'vs Red Sox',
    market: 'Runs Batted In',
    line: 'Over 0.5',
    side: 'Over',
    odds: '-110',
    openingOdds: '-125',
    l5: 77,
    l10: 71,
    l20: 74,
    l40: 70,
    season2026: 73,
    confidence: 80,
    projectedProbability: 60,
    impliedProbability: 52,
    projectedEdge: 8.2,
    recentFormScore: 8.7,
    matchupScore: 7.9,
    marketMovementScore: 7.0,
    projectedPlateAppearances: '5.4',
    weatherSummary: 'Calm winds',
    parkFactor: 'High HR park',
    pitcherSummary: 'Crochet gives up run-scoring middle innings',
    riskFactors: ['Possible low-leverage spot'],
  },
  {
    id: 'soto-runs',
    playerId: 'juan-soto',
    playerName: 'Juan Soto',
    playerImageUrl: 'JS',
    team: 'Yankees',
    teamLogoUrl: 'NYY',
    opponent: 'vs Red Sox',
    market: 'Runs',
    line: 'Over 0.5',
    side: 'Over',
    odds: '-105',
    openingOdds: '-115',
    l5: 73,
    l10: 68,
    l20: 72,
    l40: 66,
    season2026: 69,
    confidence: 74,
    projectedProbability: 56,
    impliedProbability: 51,
    projectedEdge: 5.1,
    recentFormScore: 7.4,
    matchupScore: 7.8,
    marketMovementScore: 6.4,
    projectedPlateAppearances: '4.8',
    weatherSummary: 'Warm, slight breeze',
    parkFactor: 'Neutral',
    pitcherSummary: 'Crochet has been vulnerable in the first three innings',
    riskFactors: ['Spotting for a lefty pitch mix'],
  },
  {
    id: 'ohtani-hr',
    playerId: 'shohei-ohtani',
    playerName: 'Shohei Ohtani',
    playerImageUrl: 'SO',
    team: 'Dodgers',
    teamLogoUrl: 'LAD',
    opponent: 'vs Giants',
    market: 'Home Runs',
    line: 'Over 0.5',
    side: 'Over',
    odds: '-125',
    openingOdds: '-105',
    l5: 73,
    l10: 70,
    l20: 75,
    l40: 72,
    season2026: 76,
    confidence: 82,
    projectedProbability: 60,
    impliedProbability: 56,
    projectedEdge: 4.2,
    recentFormScore: 8.4,
    matchupScore: 8.0,
    marketMovementScore: 6.9,
    projectedPlateAppearances: '5.2',
    weatherSummary: 'Wind out to left',
    parkFactor: 'Boosts fly balls',
    pitcherSummary: 'Snell is 31st in HR allowed rate',
    riskFactors: ['Swing-and-miss risk'],
  },
  {
    id: 'betts-rbi',
    playerId: 'mookie-betts',
    playerName: 'Mookie Betts',
    playerImageUrl: 'MB',
    team: 'Dodgers',
    teamLogoUrl: 'LAD',
    opponent: 'vs Giants',
    market: 'Runs Batted In',
    line: 'Over 0.5',
    side: 'Over',
    odds: '-115',
    openingOdds: '-125',
    l5: 68,
    l10: 66,
    l20: 70,
    l40: 67,
    season2026: 70,
    confidence: 73,
    projectedProbability: 55,
    impliedProbability: 53,
    projectedEdge: 2.1,
    recentFormScore: 7.0,
    matchupScore: 6.8,
    marketMovementScore: 5.6,
    projectedPlateAppearances: '4.9',
    weatherSummary: 'Calm, mild',
    parkFactor: 'Neutral',
    pitcherSummary: 'Snell has given up multiple baserunners early',
    riskFactors: ['Power outage risk'],
  },
  {
    id: 'henderson-rbi',
    playerId: 'gunnar-henderson',
    playerName: 'Gunnar Henderson',
    playerImageUrl: 'GH',
    team: 'Orioles',
    teamLogoUrl: 'BAL',
    opponent: 'vs Astros',
    market: 'Runs Batted In',
    line: 'Over 0.5',
    side: 'Over',
    odds: '-110',
    openingOdds: '-100',
    l5: 71,
    l10: 69,
    l20: 72,
    l40: 68,
    season2026: 72,
    confidence: 76,
    projectedProbability: 58,
    impliedProbability: 52,
    projectedEdge: 6.0,
    recentFormScore: 7.8,
    matchupScore: 7.6,
    marketMovementScore: 6.3,
    projectedPlateAppearances: '4.6',
    weatherSummary: 'Indoor',
    parkFactor: 'Neutral',
    pitcherSummary: 'Hunter Brown gives up middle-middle contact',
    riskFactors: ['Potential batting order movement'],
  },
  {
    id: 'turner-hits',
    playerId: 'trea-turner',
    playerName: 'Trea Turner',
    playerImageUrl: 'TT',
    team: 'Phillies',
    teamLogoUrl: 'PHI',
    opponent: 'vs Marlins',
    market: 'Hits',
    line: 'Over 0.5',
    side: 'Over',
    odds: '-120',
    openingOdds: '-125',
    l5: 64,
    l10: 65,
    l20: 67,
    l40: 62,
    season2026: 68,
    confidence: 69,
    projectedProbability: 54,
    impliedProbability: 55,
    projectedEdge: -0.8,
    recentFormScore: 6.7,
    matchupScore: 6.6,
    marketMovementScore: 5.3,
    projectedPlateAppearances: '4.4',
    weatherSummary: 'Humid, warm',
    parkFactor: 'Neutral',
    pitcherSummary: 'Cabrera is prone to early count mistakes',
    riskFactors: ['High variance on contact quality'],
  },
  {
    id: 'valdez-k',
    playerId: 'framber-valdez',
    playerName: 'Framber Valdez',
    playerImageUrl: 'FV',
    team: 'Astros',
    teamLogoUrl: 'HOU',
    opponent: 'vs Orioles',
    market: 'Strikeouts',
    line: 'Over 5.5',
    side: 'Over',
    odds: '-125',
    openingOdds: '+105',
    l5: 63,
    l10: 65,
    l20: 66,
    l40: 64,
    season2026: 68,
    confidence: 71,
    projectedProbability: 55,
    impliedProbability: 56,
    projectedEdge: -0.8,
    recentFormScore: 7.1,
    matchupScore: 7.0,
    marketMovementScore: 6.1,
    projectedPlateAppearances: 'N/A',
    weatherSummary: 'Indoor park',
    parkFactor: 'Neutral',
    pitcherSummary: 'Orioles are weak to lefty spin',
    riskFactors: ['Pitch count limits'],
  },
  {
    id: 'judge-runs',
    playerId: 'aaron-judge',
    playerName: 'Aaron Judge',
    playerImageUrl: 'AJ',
    team: 'Yankees',
    teamLogoUrl: 'NYY',
    opponent: 'vs Red Sox',
    market: 'Runs',
    line: 'Over 0.5',
    side: 'Over',
    odds: '-125',
    openingOdds: '-110',
    l5: 78,
    l10: 72,
    l20: 74,
    l40: 70,
    season2026: 74,
    confidence: 83,
    projectedProbability: 62,
    impliedProbability: 56,
    projectedEdge: 6.4,
    recentFormScore: 8.8,
    matchupScore: 8.2,
    marketMovementScore: 7.4,
    projectedPlateAppearances: '5.4',
    weatherSummary: 'Calm winds',
    parkFactor: 'High HR park',
    pitcherSummary: 'Crochet is giving up too many middle innings',
    riskFactors: ['Can be a one-plate-appearance swing'],
  },
  {
    id: 'skenes-ips',
    playerId: 'paul-skenes',
    playerName: 'Paul Skenes',
    playerImageUrl: 'PS',
    team: 'Pirates',
    teamLogoUrl: 'PIT',
    opponent: 'vs Cubs',
    market: 'Innings Pitched',
    line: 'Over 5.5',
    side: 'Over',
    odds: '-115',
    openingOdds: '-105',
    l5: 61,
    l10: 63,
    l20: 64,
    l40: 62,
    season2026: 67,
    confidence: 68,
    projectedProbability: 53,
    impliedProbability: 53,
    projectedEdge: 0.1,
    recentFormScore: 6.9,
    matchupScore: 6.5,
    marketMovementScore: 5.7,
    projectedPlateAppearances: 'N/A',
    weatherSummary: 'Windy, cool',
    parkFactor: 'Neutral',
    pitcherSummary: 'Cubs are swing-heavy early',
    riskFactors: ['Pitch count volatility'],
  },
  {
    id: 'henderson-hits',
    playerId: 'gunnar-henderson',
    playerName: 'Gunnar Henderson',
    playerImageUrl: 'GH',
    team: 'Orioles',
    teamLogoUrl: 'BAL',
    opponent: 'vs Astros',
    market: 'Hits',
    line: 'Over 0.5',
    side: 'Over',
    odds: '-115',
    openingOdds: '-105',
    l5: 72,
    l10: 70,
    l20: 73,
    l40: 69,
    season2026: 71,
    confidence: 78,
    projectedProbability: 59,
    impliedProbability: 53,
    projectedEdge: 6.1,
    recentFormScore: 7.9,
    matchupScore: 7.5,
    marketMovementScore: 6.8,
    projectedPlateAppearances: '4.6',
    weatherSummary: 'Indoor',
    parkFactor: 'Neutral',
    pitcherSummary: 'Brown is allowing barrels to left-handed hitters',
    riskFactors: ['Lineup shift risk'],
  },
  {
    id: 'valdez-er',
    playerId: 'framber-valdez',
    playerName: 'Framber Valdez',
    playerImageUrl: 'FV',
    team: 'Astros',
    teamLogoUrl: 'HOU',
    opponent: 'vs Orioles',
    market: 'Earned Runs',
    line: 'Under 1.5',
    side: 'Under',
    odds: '+115',
    openingOdds: '+125',
    l5: 62,
    l10: 64,
    l20: 65,
    l40: 66,
    season2026: 67,
    confidence: 72,
    projectedProbability: 56,
    impliedProbability: 47,
    projectedEdge: 9.1,
    recentFormScore: 7.3,
    matchupScore: 7.9,
    marketMovementScore: 6.7,
    projectedPlateAppearances: 'N/A',
    weatherSummary: 'Indoor park',
    parkFactor: 'Neutral',
    pitcherSummary: 'Orioles are weak vs sinker-slider mix',
    riskFactors: ['Bullpen usage risk'],
  },
  {
    id: 'schwarber-hr',
    playerId: 'kyle-schwarber',
    mlbPlayerId: 656941,
    playerName: 'Kyle Schwarber',
    playerImageUrl: 'KS',
    team: 'Phillies',
    teamId: 143,
    teamLogoUrl: 'PHI',
    opponent: 'vs Marlins',
    opponentTeamId: 146,
    market: 'Home Runs',
    line: 'Over 0.5',
    side: 'Over',
    odds: '+100',
    openingOdds: '+115',
    l5: 68, l10: 70, l20: 66, l40: 71, season2026: 64,
    confidence: 72,
    projectedProbability: 52, impliedProbability: 48, projectedEdge: 4.8,
    recentFormScore: 7.8, matchupScore: 7.2, marketMovementScore: 6.4,
    projectedPlateAppearances: '4.9',
    weatherSummary: 'Warm, humid conditions indoors',
    parkFactor: 'Neutral',
    pitcherSummary: 'Marlins starter allows 1.1 HR/9',
    riskFactors: ['Elevated strikeout risk', 'Moderate walk rate'],
  },
  {
    id: 'trout-hits',
    playerId: 'mike-trout',
    mlbPlayerId: 545361,
    playerName: 'Mike Trout',
    playerImageUrl: 'MT',
    team: 'Angels',
    teamId: 108,
    teamLogoUrl: 'LAA',
    opponent: 'vs Rangers',
    opponentTeamId: 140,
    market: 'Hits',
    line: 'Over 0.5',
    side: 'Over',
    odds: '-105',
    openingOdds: '-100',
    l5: 60, l10: 60, l20: 63, l40: 61, season2026: 60,
    confidence: 64,
    projectedProbability: 50, impliedProbability: 48, projectedEdge: 2.1,
    recentFormScore: 7.0, matchupScore: 6.8, marketMovementScore: 5.9,
    projectedPlateAppearances: '4.5',
    weatherSummary: 'Outdoor, mild conditions',
    parkFactor: 'Neutral',
    pitcherSummary: 'Rangers starter with 3.67 ERA',
    riskFactors: ['Injury return — limited sample', 'Rust factor'],
  },
  {
    id: 'alvarez-hr',
    playerId: 'yordan-alvarez',
    mlbPlayerId: 670541,
    playerName: 'Yordan Alvarez',
    playerImageUrl: 'YA',
    team: 'Astros',
    teamId: 117,
    teamLogoUrl: 'HOU',
    opponent: 'vs Athletics',
    opponentTeamId: 133,
    market: 'Home Runs',
    line: 'Over 0.5',
    side: 'Over',
    odds: '+115',
    openingOdds: '+125',
    l5: 50, l10: 50, l20: 55, l40: 58, season2026: 56,
    confidence: 60,
    projectedProbability: 47, impliedProbability: 45, projectedEdge: 1.6,
    recentFormScore: 7.2, matchupScore: 6.5, marketMovementScore: 7.1,
    projectedPlateAppearances: '5.0',
    weatherSummary: 'Indoor dome',
    parkFactor: 'Neutral dome',
    pitcherSummary: 'Athletics starter with 4.8 ERA, 1.1 HR/9',
    riskFactors: ['Cold stretch last 5 games'],
  },
  {
    id: 'devers-hits',
    playerId: 'rafael-devers',
    mlbPlayerId: 646240,
    playerName: 'Rafael Devers',
    playerImageUrl: 'RD',
    team: 'Red Sox',
    teamId: 111,
    teamLogoUrl: 'BOS',
    opponent: 'vs Yankees',
    opponentTeamId: 147,
    market: 'Hits',
    line: 'Over 1.5',
    side: 'Over',
    odds: '-110',
    openingOdds: '-100',
    l5: 60, l10: 60, l20: 61, l40: 64, season2026: 62,
    confidence: 58,
    projectedProbability: 46, impliedProbability: 45, projectedEdge: 0.8,
    recentFormScore: 6.8, matchupScore: 6.2, marketMovementScore: 6.1,
    projectedPlateAppearances: '4.7',
    weatherSummary: 'Windy at Fenway',
    parkFactor: 'Moderate HR factor',
    pitcherSummary: 'Yankees starter with 3.92 ERA',
    riskFactors: ['Facing elite pitcher', 'Cold bat last 3 games'],
  },
  {
    id: 'julio-tb',
    playerId: 'julio-rodriguez',
    mlbPlayerId: 677594,
    playerName: 'Julio Rodriguez',
    playerImageUrl: 'JR',
    team: 'Mariners',
    teamId: 136,
    teamLogoUrl: 'SEA',
    opponent: 'vs Rays',
    opponentTeamId: 139,
    market: 'Total Bases',
    line: 'Over 1.5',
    side: 'Over',
    odds: '-105',
    openingOdds: '-100',
    l5: 60, l10: 60, l20: 63, l40: 61, season2026: 60,
    confidence: 58,
    projectedProbability: 46, impliedProbability: 45, projectedEdge: 0.4,
    recentFormScore: 6.5, matchupScore: 6.3, marketMovementScore: 5.7,
    projectedPlateAppearances: '4.8',
    weatherSummary: 'Indoor dome',
    parkFactor: 'Neutral',
    pitcherSummary: 'Rays starter with 3.85 ERA',
    riskFactors: ['Facing quality pitching', 'Below average recent TB'],
  },
];

const categoryByScore: Record<PickCategory, number> = {
  'Top Picks': 0,
  'High Confidence': 1,
  Value: 2,
  Trending: 3,
  'Market Movers': 4,
  'My Saved': 5,
};

export const picksData: PickRecord[] = basePicks.map((pick, index) => {
  const opportunityScore = Math.round(
    pick.confidence * 0.4 + pick.projectedEdge * 0.25 + pick.recentFormScore * 0.2 + pick.matchupScore * 0.1 + pick.marketMovementScore * 0.05
  );

  const category: PickCategory = pick.confidence >= 82 || opportunityScore >= 82
    ? 'High Confidence'
    : pick.projectedEdge >= 6
      ? 'Value'
      : pick.marketMovementScore >= 7.5 || pick.recentFormScore >= 8.5
        ? 'Trending'
        : 'Top Picks';

  const marketMovement = pick.marketMovementScore >= 7.5 ? 'Steam Up' : pick.marketMovementScore >= 6.5 ? 'Moving Up' : 'Stable';
  const description = `${pick.market} • ${pick.line} • ${pick.team} vs ${pick.opponent}`;
  const insight = pick.confidence >= 80
    ? `${pick.playerName} has a premium edge in this spot based on recent form and matchup.`
    : `${pick.playerName} carries a solid but less explosive opportunity profile.`;

  return {
    ...pick,
    opportunityScore,
    category,
    insight,
    marketMovement,
    description,
    researchHref: `/research/${pick.playerId}`,
  };
}).sort((a, b) => b.opportunityScore - a.opportunityScore);

export const pickCategories: PickCategory[] = ['Top Picks', 'High Confidence', 'Value', 'Trending', 'Market Movers'];
export const pickSortOptions: PickSort[] = ['Highest Confidence', 'Best L5', 'Best L10', 'Best L20', 'Best L40', 'Best 2026', 'Best Value', 'Biggest Market Move'];
export const quickInsights = [
  'Judge has homered in 4 of last 5 games.',
  'Wind blowing out at Wrigley for a premium K prop.',
  'Bullpen usage is elevated for the home side.',
  'Pitcher K rate is down over the last 3 starts.',
  'Line moved 22 cents toward the Over.',
];

export const savedPreview = [
  { player: 'Aaron Judge', prop: 'Home Runs', line: 'Over 0.5', confidence: 86 },
  { player: 'Shohei Ohtani', prop: 'Total Bases', line: 'Over 1.5', confidence: 84 },
];

export const alerts = [
  { label: 'Line movement', detail: 'Judge moved 18 cents toward Over' },
  { label: 'Pitcher scratch', detail: 'Weather check for a late swap' },
  { label: 'Weather change', detail: 'Wrigley wind shifted 8 mph' },
];
